// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package xray

const (

	// ErrCodeInvalidRequestException for service response error code
	// "InvalidRequestException".
	//
	// The request is missing required parameters or has invalid parameters.
	ErrCodeInvalidRequestException = "InvalidRequestException"

	// ErrCodeThrottledException for service response error code
	// "ThrottledException".
	//
	// The request exceeds the maximum number of requests per second.
	ErrCodeThrottledException = "ThrottledException"
)
//Added a line for testing
//Adding another line for Git event testing part 2
//Adding another line for Git event testing part 2.1
//Adding another line for Git event testing part 2.2
