// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package athena

const (

	// ErrCodeInternalServerException for service response error code
	// "InternalServerException".
	//
	// Indicates a platform issue, which may be due to a transient condition or
	// outage.
	ErrCodeInternalServerException = "InternalServerException"

	// ErrCodeInvalidRequestException for service response error code
	// "InvalidRequestException".
	//
	// Indicates that something is wrong with the input to the request. For example,
	// a required parameter may be missing or out of range.
	ErrCodeInvalidRequestException = "InvalidRequestException"

	// ErrCodeTooManyRequestsException for service response error code
	// "TooManyRequestsException".
	//
	// Indicates that the request was throttled.
	ErrCodeTooManyRequestsException = "TooManyRequestsException"
)
//Added a line for testing
//Adding another line for Git event testing part 2
//Adding another line for Git event testing part 2.1
