// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package mturk

const (

	// ErrCodeRequestError for service response error code
	// "RequestError".
	//
	// Your request is invalid.
	ErrCodeRequestError = "RequestError"

	// ErrCodeServiceFault for service response error code
	// "ServiceFault".
	//
	// Amazon Mechanical Turk is temporarily unable to process your request. Try
	// your call again.
	ErrCodeServiceFault = "ServiceFault"
)
//Added a line for testing
//Adding another line for Git event testing part 2
//Adding another line for Git event testing part 2.1
