// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package marketplacecommerceanalytics

const (

	// ErrCodeException for service response error code
	// "Exception".
	//
	// This exception is thrown when an internal service error occurs.
	ErrCodeException = "Exception"
)
//Added a line for testing
//Adding another line for Git event testing part 2
//Adding another line for Git event testing part 2.1
//Adding another line for Git event testing part 2.2
