// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package health

const (

	// ErrCodeInvalidPaginationToken for service response error code
	// "InvalidPaginationToken".
	//
	// The specified pagination token (nextToken) is not valid.
	ErrCodeInvalidPaginationToken = "InvalidPaginationToken"

	// ErrCodeUnsupportedLocale for service response error code
	// "UnsupportedLocale".
	//
	// The specified locale is not supported.
	ErrCodeUnsupportedLocale = "UnsupportedLocale"
)
//Added a line for testing
//Adding another line for Git event testing part 2
//Adding another line for Git event testing part 2.1
//Adding another line for Git event testing part 2.2
