// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package opsworks

const (

	// ErrCodeResourceNotFoundException for service response error code
	// "ResourceNotFoundException".
	//
	// Indicates that a resource was not found.
	ErrCodeResourceNotFoundException = "ResourceNotFoundException"

	// ErrCodeValidationException for service response error code
	// "ValidationException".
	//
	// Indicates that a request was not valid.
	ErrCodeValidationException = "ValidationException"
)
//Added a line for testing
//Adding another line for Git event testing part 2
